// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
class_name CourierEnvelope
## 信封 wire key 常量与判定(primitives.md Frozen v1)。
## GDScript 以 Dictionary 承载线格式,key 常量即 DTO 对齐锚点。

const KEY_DATA := "data"      # 成功信封只有 data,不携带 traceId
const KEY_ERROR := "error"     # 失败信封 error + traceId,与 data 互斥
const KEY_TRACE_ID := "traceId"  # 只在失败响应 body
const KEY_CODE := "code"
const KEY_MESSAGE := "message"
const KEY_RETRYABLE := "retryable"
const KEY_ITEMS := "items"
const KEY_NEXT_CURSOR := "nextCursor"  # 缺失/空 = 末页

# scope 头(game_id + env,scope.md Frozen v1):
const HEADER_GAME_ID := "X-Courier-Game-Id"
const HEADER_ENV := "X-Courier-Env"
const ENVS: PackedStringArray = ["dev", "staging", "prod"]

static func is_failure(body: Dictionary) -> bool:
	return body.has(KEY_ERROR)

static func trace_id_of(body: Dictionary) -> String:
	return str(body.get(KEY_TRACE_ID, ""))
