// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
class_name CourierErrorCode
## 契约错误码(v1 冻结集);未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。

## 域前缀注册表(新域先注册前缀再定义码)。
const PREFIXES: PackedStringArray = ["COMMON", "AUTH", "SESSION", "SCOPE", "RATE", "ANNOUNCEMENT", "SUPPORT", "ASSISTANT", "PAYMENT", "REALNAME", "CONFIG", "APP", "DIAG"]

## 冻结映射:wire code → { http, retryable }。
const SPECS: Dictionary = {
	"COMMON_INTERNAL": {"http": 500, "retryable": true},
	"COMMON_INVALID_ARGUMENT": {"http": 400, "retryable": false},
	"COMMON_UNAUTHENTICATED": {"http": 401, "retryable": false},
	"COMMON_PERMISSION_DENIED": {"http": 403, "retryable": false},
	"COMMON_NOT_FOUND": {"http": 404, "retryable": false},
	"COMMON_CAPABILITY_DISABLED": {"http": 501, "retryable": false},
	"COMMON_UNAVAILABLE": {"http": 503, "retryable": true},
	"RATE_LIMITED": {"http": 429, "retryable": true},
	"SCOPE_MISMATCH": {"http": 400, "retryable": false},
	"AUTH_INVALID_CREDENTIALS": {"http": 401, "retryable": false},
	"AUTH_TOKEN_EXPIRED": {"http": 401, "retryable": false},
	"AUTH_TOKEN_REVOKED": {"http": 401, "retryable": false},
	"AUTH_REFRESH_REUSED": {"http": 401, "retryable": false},
	"AUTH_ACCOUNT_DISABLED": {"http": 403, "retryable": false},
	"AUTH_DEVICE_LIMIT": {"http": 403, "retryable": false},
	"AUTH_EMAIL_TAKEN": {"http": 409, "retryable": false},
	"SESSION_CONFLICT": {"http": 409, "retryable": false},
	"ANNOUNCEMENT_NOT_FOUND": {"http": 404, "retryable": false},
	"SUPPORT_TICKET_NOT_FOUND": {"http": 404, "retryable": false},
	"SUPPORT_TICKET_CLOSED": {"http": 409, "retryable": false},
	"REALNAME_REQUIRED": {"http": 403, "retryable": false},
	"REALNAME_REJECTED": {"http": 403, "retryable": false},
	"REALNAME_PENDING_REVIEW": {"http": 403, "retryable": false},
	"REALNAME_CURFEW_BLOCKED": {"http": 403, "retryable": false},
	"REALNAME_CHARGE_BLOCKED": {"http": 403, "retryable": false},
	"CONFIG_NOT_FOUND": {"http": 404, "retryable": false},
	"APP_MAINTENANCE": {"http": 503, "retryable": false},
	"APP_VERSION_UNSUPPORTED": {"http": 426, "retryable": false},
}

const NAME_TO_WIRE: Dictionary = {
	"CommonInternal": "COMMON_INTERNAL",
	"CommonInvalidArgument": "COMMON_INVALID_ARGUMENT",
	"CommonUnauthenticated": "COMMON_UNAUTHENTICATED",
	"CommonPermissionDenied": "COMMON_PERMISSION_DENIED",
	"CommonNotFound": "COMMON_NOT_FOUND",
	"CommonCapabilityDisabled": "COMMON_CAPABILITY_DISABLED",
	"CommonUnavailable": "COMMON_UNAVAILABLE",
	"RateLimited": "RATE_LIMITED",
	"ScopeMismatch": "SCOPE_MISMATCH",
	"AuthInvalidCredentials": "AUTH_INVALID_CREDENTIALS",
	"AuthTokenExpired": "AUTH_TOKEN_EXPIRED",
	"AuthTokenRevoked": "AUTH_TOKEN_REVOKED",
	"AuthRefreshReused": "AUTH_REFRESH_REUSED",
	"AuthAccountDisabled": "AUTH_ACCOUNT_DISABLED",
	"AuthDeviceLimit": "AUTH_DEVICE_LIMIT",
	"AuthEmailTaken": "AUTH_EMAIL_TAKEN",
	"SessionConflict": "SESSION_CONFLICT",
	"AnnouncementNotFound": "ANNOUNCEMENT_NOT_FOUND",
	"SupportTicketNotFound": "SUPPORT_TICKET_NOT_FOUND",
	"SupportTicketClosed": "SUPPORT_TICKET_CLOSED",
	"RealnameRequired": "REALNAME_REQUIRED",
	"RealnameRejected": "REALNAME_REJECTED",
	"RealnamePendingReview": "REALNAME_PENDING_REVIEW",
	"RealnameCurfewBlocked": "REALNAME_CURFEW_BLOCKED",
	"RealnameChargeBlocked": "REALNAME_CHARGE_BLOCKED",
	"ConfigNotFound": "CONFIG_NOT_FOUND",
	"AppMaintenance": "APP_MAINTENANCE",
	"AppVersionUnsupported": "APP_VERSION_UNSUPPORTED",
}

## wire code → 枚举名;未知返回 ""(调用方落兜底分支)。
static func name_of(wire: String) -> String:
	for name in NAME_TO_WIRE:
		if NAME_TO_WIRE[name] == wire:
			return name
	return ""

static func spec_of(wire: String) -> Dictionary:
	return SPECS.get(wire, {})
