// contractgen 从 docs/contract/fixtures 生成各端契约源(错误枚举 + 信封 DTO),
// 落点「契约测试骨架(各端错误枚举/DTO 对齐断言)」:生成物与 fixture 不漂移。
//
// 用法(仓库根):
//
//	go run ./tools/contractgen            # 校验:生成结果与仓内文件逐字节比对,漂移即非零退出
//	go run ./tools/contractgen -write     # 重新生成(改 fixture 后执行)
//
// 生成物头部均带 DO NOT EDIT;契约事实源是 docs/contract/*.md(Frozen v1)。
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type codeRow struct {
	Code      string `json:"code"`
	HTTP      int    `json:"http"`
	Retryable bool   `json:"retryable"`
}

type errorsFixture struct {
	Version  int       `json:"version"`
	Prefixes []string  `json:"prefixes"`
	Codes    []codeRow `json:"codes"`
}

type scopeFixture struct {
	Version int               `json:"version"`
	Headers map[string]string `json:"headers"`
	Envs    []string          `json:"envs"`
}

type dtoFixture struct {
	Version int               `json:"version"`
	Keys    map[string]string `json:"keys"`
}

func readJSON(path string, v any) {
	raw, err := os.ReadFile(path)
	if err != nil {
		fatal("读 fixture: %v", err)
	}
	if err := json.Unmarshal(raw, v); err != nil {
		fatal("解析 %s: %v", path, err)
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "contractgen: "+format+"\n", args...)
	os.Exit(1)
}

// camelName COMMON_INTERNAL → CommonInternal(各端枚举成员命名,语言习惯内统一)。
func camelName(wire string) string {
	parts := strings.Split(wire, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, "")
}

// generate 返回 相对仓库根路径 → 文件内容。仅 stdlib,无外部依赖。
func generate(root string) map[string][]byte {
	ef := &errorsFixture{}
	readJSON(filepath.Join(root, "docs", "contract", "fixtures", "errors.json"), ef)
	sf := &scopeFixture{}
	readJSON(filepath.Join(root, "docs", "contract", "fixtures", "scope.json"), sf)
	df := &dtoFixture{}
	readJSON(filepath.Join(root, "docs", "contract", "fixtures", "dto.json"), df)

	if ef.Version != 1 || len(ef.Codes) == 0 || len(ef.Prefixes) == 0 {
		fatal("errors fixture 不完整: version=%d codes=%d prefixes=%d", ef.Version, len(ef.Codes), len(ef.Prefixes))
	}
	for _, k := range []string{"data", "error", "traceId", "code", "message", "retryable", "items", "nextCursor"} {
		if df.Keys[k] == "" {
			fatal("dto fixture 缺 key %q", k)
		}
	}

	out := map[string][]byte{}
	put := func(rel, content string) {
		out[filepath.FromSlash(rel)] = []byte(strings.TrimRight(content, "\n") + "\n")
	}

	put("sdks/unity/Runtime/Core/Contract/ErrorCode.cs", genCsErrors(ef))
	put("sdks/unity/Runtime/Core/Contract/Envelope.cs", genCsEnvelope(df))
	for _, end := range []string{"cocos", "miniprogram", "laybox"} {
		put(fmt.Sprintf("sdks/%s/src/contract/errors.ts", end), genTsErrors(ef))
		put(fmt.Sprintf("sdks/%s/src/contract/envelope.ts", end), genTsEnvelope(df))
	}
	put("sdks/ue/contract/errors.hpp", genCppErrors(ef))
	put("sdks/ue/contract/envelope.hpp", genCppEnvelope(df))
	put("sdks/godot/contract/errors.gd", genGdErrors(ef))
	put("sdks/godot/contract/envelope.gd", genGdEnvelope(df, sf))
	return out
}

func checkOrWrite(root string, write bool) {
	files := generate(root)
	drift := false
	for rel, want := range files {
		path := filepath.Join(root, rel)
		have, err := os.ReadFile(path)
		switch {
		case os.IsNotExist(err):
			drift = true
			fmt.Printf("缺失: %s\n", rel)
		case err != nil:
			fatal("读 %s: %v", rel, err)
		case write && !bytes.Equal(have, want):
			drift = true
			fmt.Printf("更新: %s\n", rel)
		case !write && !bytes.Equal(have, want):
			drift = true
			fmt.Printf("漂移: %s(与 fixture 不一致)\n", rel)
		}
		if write {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				fatal("建目录 %s: %v", rel, err)
			}
			if err := os.WriteFile(path, want, 0o644); err != nil {
				fatal("写 %s: %v", rel, err)
			}
		}
	}
	if drift {
		if write {
			fmt.Println("生成完成。")
		} else {
			fatal("生成物与仓内文件不一致;运行 go run ./tools/contractgen -write 重新生成")
		}
		return
	}
	fmt.Println("生成物与仓内文件一致。")
}

func main() {
	write := flag.Bool("write", false, "写入生成文件(默认校验模式)")
	root := flag.String("root", ".", "仓库根目录")
	flag.Parse()
	checkOrWrite(*root, *write)
}

const genBanner = "// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.\n// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write\n"

// --- Unity (C#) ---

func genCsErrors(ef *errorsFixture) string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("//\nnamespace Courier.Contract\n{\n")
	b.WriteString("    /// <summary>契约错误码(v1 冻结集)。未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。</summary>\n")
	b.WriteString("    public enum ErrorCode\n    {\n")
	for i, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("        %s = %d,\n", camelName(c.Code), i))
	}
	b.WriteString("    }\n\n")
	b.WriteString("    /// <summary>错误码 → wire / HTTP / retryable 冻结映射(下标与枚举值对齐)。</summary>\n")
	b.WriteString("    public static class ErrorSpecs\n    {\n")
	b.WriteString("        public sealed class Spec\n        {\n")
	b.WriteString("            public string Wire { get; }\n            public int Http { get; }\n            public bool Retryable { get; }\n")
	b.WriteString("            internal Spec(string wire, int http, bool retryable) { Wire = wire; Http = http; Retryable = retryable; }\n        }\n\n")
	b.WriteString("        static readonly Spec[] Ordered =\n        {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("            new Spec(\"%s\", %d, %s),\n", c.Code, c.HTTP, lower(c.Retryable)))
	}
	b.WriteString("        };\n\n")
	b.WriteString("        /// <summary>域前缀注册表(新域先注册前缀再定义码)。</summary>\n")
	b.WriteString("        public static readonly string[] Prefixes = { " + quoteJoin(ef.Prefixes) + " };\n\n")
	b.WriteString("        /// <summary>全部冻结码(供契约测试对账)。</summary>\n")
	b.WriteString("        public static System.Collections.Generic.IReadOnlyList<Spec> All\n        {\n            get { return Ordered; }\n        }\n\n")
	b.WriteString("        public static bool TryGet(ErrorCode code, out Spec spec)\n        {\n")
	b.WriteString("            int i = (int)code;\n            if (i < 0 || i >= Ordered.Length) { spec = null; return false; }\n")
	b.WriteString("            spec = Ordered[i]; return true;\n        }\n\n")
	b.WriteString("        /// <summary>wire code → 枚举;未知返回 false(调用方落兜底分支)。</summary>\n")
	b.WriteString("        public static bool TryParse(string wire, out ErrorCode code)\n        {\n")
	b.WriteString("            for (int i = 0; i < Ordered.Length; i++)\n            {\n                if (Ordered[i].Wire == wire) { code = (ErrorCode)i; return true; }\n            }\n")
	b.WriteString("            code = default; return false;\n        }\n    }\n}\n")
	return b.String()
}

func genCsEnvelope(df *dtoFixture) string {
	k := df.Keys
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("//\nnamespace Courier.Contract\n{\n")
	fmt.Fprintf(&b, `    /// <summary>失败响应 error 体(wire: %s/%s/%s)。code 为 wire 字符串,未知码容忍。</summary>
    public sealed class ApiError
    {
        public const string KeyCode = "%s";
        public const string KeyMessage = "%s";
        public const string KeyRetryable = "%s";
        public string Code { get; set; }
        public string Message { get; set; }
        public bool Retryable { get; set; }
    }

    /// <summary>失败信封(wire: %s + %s;与 data 互斥,traceId 只在失败响应 body)。</summary>
    public sealed class ErrorEnvelope
    {
        public const string KeyError = "%s";
        public const string KeyTraceId = "%s";
        public ApiError Error { get; set; }
        public string TraceId { get; set; }
    }

    /// <summary>成功信封(wire: 只有 %s,不携带 traceId)。</summary>
    public sealed class SuccessEnvelope<T>
    {
        public const string KeyData = "%s";
        public T Data { get; set; }
    }

    /// <summary>游标分页(%s + %s;缺失/空 = 末页)。</summary>
    public sealed class Page<T>
    {
        public const string KeyItems = "%s";
        public const string KeyNextCursor = "%s";
        public System.Collections.Generic.List<T> Items { get; set; }
        public string NextCursor { get; set; }
    }
}
`, k["code"], k["message"], k["retryable"], k["code"], k["message"], k["retryable"],
		k["error"], k["traceId"], k["error"], k["traceId"],
		k["data"], k["data"],
		k["items"], k["nextCursor"], k["items"], k["nextCursor"])
	return b.String()
}

// --- TypeScript (Cocos / 小程序 / Layabox) ---

func genTsErrors(ef *errorsFixture) string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("/** 契约错误码(wire 值);未知 code 必须容忍,落到兜底分支(契约 versioning.md)。 */\n")
	b.WriteString("export const ErrorCode = {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("  %s: \"%s\",\n", camelName(c.Code), c.Code))
	}
	b.WriteString("} as const;\nexport type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];\n\n")
	b.WriteString("export interface ErrorSpec {\n  readonly wire: ErrorCode;\n  readonly http: number;\n  readonly retryable: boolean;\n}\n\n")
	b.WriteString("/** 冻结映射:错误码 → wire / HTTP / retryable。 */\n")
	b.WriteString("export const ErrorSpecs: Readonly<Record<ErrorCode, ErrorSpec>> = {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("  %s: { wire: \"%s\", http: %d, retryable: %s },\n", camelName(c.Code), c.Code, c.HTTP, lower(c.Retryable)))
	}
	b.WriteString("};\n\n")
	b.WriteString("/** wire code → 枚举;未知返回 undefined(调用方落兜底分支)。 */\n")
	b.WriteString("export function errorCodeOf(wire: string): ErrorCode | undefined {\n  for (const key of Object.keys(ErrorSpecs) as ErrorCode[]) {\n    if (ErrorSpecs[key].wire === wire) return key;\n  }\n  return undefined;\n}\n\n")
	b.WriteString("/** 域前缀注册表(新域先注册前缀再定义码)。 */\n")
	b.WriteString("export const ERROR_PREFIXES = [" + tsQuoteJoin(ef.Prefixes) + "] as const;\nexport type ErrorPrefix = (typeof ERROR_PREFIXES)[number];\n")
	return b.String()
}

func genTsEnvelope(df *dtoFixture) string {
	k := df.Keys
	var b strings.Builder
	b.WriteString(genBanner)
	fmt.Fprintf(&b, `/** 失败响应 error 体(wire keys: %s/%s/%s)。 */
export interface ApiError {
  readonly code: string;
  readonly message: string;
  readonly retryable: boolean;
}

/** 失败信封:%s + %s,与 data 互斥;traceId 只在失败响应 body。 */
export interface ErrorEnvelope {
  readonly error: ApiError;
  readonly traceId: string;
}

/** 成功信封:只有 %s,不携带 traceId。 */
export interface SuccessEnvelope<T> {
  readonly data: T;
}

/** 游标分页:%s + %s;缺失/空 = 末页。 */
export interface Page<T> {
  readonly items: readonly T[];
  readonly nextCursor?: string;
}
`, k["code"], k["message"], k["retryable"], k["error"], k["traceId"], k["data"], k["items"], k["nextCursor"])
	return b.String()
}

// --- UE (C++17,无引擎依赖,UBT 接入前可独立编译) ---

func genCppErrors(ef *errorsFixture) string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("#ifndef COURIER_CONTRACT_ERRORS_HPP\n#define COURIER_CONTRACT_ERRORS_HPP\n\n#include <cstddef>\n#include <cstring>\n\nnamespace courier {\n\n")
	b.WriteString("/// 契约错误码(v1 冻结集);未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。\n")
	b.WriteString("enum class ErrorCode {\n")
	for i, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("    %s = %d,\n", camelName(c.Code), i))
	}
	b.WriteString("    kCount  // 哨兵,非契约码\n};\n\n")
	b.WriteString("struct ErrorSpec {\n    const char* wire;\n    int http;\n    bool retryable;\n};\n\n")
	b.WriteString("/// 冻结映射:下标与 ErrorCode 枚举值对齐。\n")
	b.WriteString("inline const ErrorSpec& error_spec(ErrorCode code) {\n    static const ErrorSpec kSpecs[] = {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("        {\"%s\", %d, %s},\n", c.Code, c.HTTP, lower(c.Retryable)))
	}
	b.WriteString("    };\n    return kSpecs[static_cast<std::size_t>(code)];\n}\n\n")
	b.WriteString("/// wire code → 枚举;未知返回 false(调用方落兜底分支)。\n")
	b.WriteString("inline bool parse_error_code(const char* wire, ErrorCode& out) {\n")
	b.WriteString("    for (int i = 0; i < static_cast<int>(ErrorCode::kCount); i++) {\n")
	b.WriteString("        const ErrorSpec& s = error_spec(static_cast<ErrorCode>(i));\n")
	b.WriteString("        if (std::strcmp(s.wire, wire) == 0) { out = static_cast<ErrorCode>(i); return true; }\n    }\n")
	b.WriteString("    return false;\n}\n\n")
	b.WriteString("/// 域前缀注册表(新域先注册前缀再定义码)。\n")
	b.WriteString("inline const char* const* error_prefixes(std::size_t& count) {\n")
	b.WriteString("    static const char* const kPrefixes[] = { " + cppQuoteJoin(ef.Prefixes) + " };\n")
	b.WriteString("    count = sizeof(kPrefixes) / sizeof(kPrefixes[0]);\n    return kPrefixes;\n}\n\n}  // namespace courier\n\n#endif  // COURIER_CONTRACT_ERRORS_HPP\n")
	return b.String()
}

func genCppEnvelope(df *dtoFixture) string {
	k := df.Keys
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("#ifndef COURIER_CONTRACT_ENVELOPE_HPP\n#define COURIER_CONTRACT_ENVELOPE_HPP\n\n#include <string>\n#include <vector>\n\nnamespace courier {\n\n")
	fmt.Fprintf(&b, `/// 失败响应 error 体(wire keys: %s/%s/%s)。
struct ApiError {
    static constexpr const char* kKeyCode = "%s";
    static constexpr const char* kKeyMessage = "%s";
    static constexpr const char* kKeyRetryable = "%s";
    std::string code;
    std::string message;
    bool retryable = false;
};

/// 失败信封:%s + %s,与 data 互斥;traceId 只在失败响应 body。
struct ErrorEnvelope {
    static constexpr const char* kKeyError = "%s";
    static constexpr const char* kKeyTraceId = "%s";
    ApiError error;
    std::string traceId;
};

/// 成功信封:只有 %s,不携带 traceId。
template <typename T>
struct SuccessEnvelope {
    static constexpr const char* kKeyData = "%s";
    T data;
};

/// 游标分页:%s + %s;缺失/空 = 末页。
template <typename T>
struct Page {
    static constexpr const char* kKeyItems = "%s";
    static constexpr const char* kKeyNextCursor = "%s";
    std::vector<T> items;
    std::string nextCursor;
};

}  // namespace courier

#endif  // COURIER_CONTRACT_ENVELOPE_HPP
`, k["code"], k["message"], k["retryable"], k["code"], k["message"], k["retryable"],
		k["error"], k["traceId"], k["error"], k["traceId"],
		k["data"], k["data"],
		k["items"], k["nextCursor"], k["items"], k["nextCursor"])
	return b.String()
}

// --- Godot (GDScript 2.0,Godot 4) ---

func genGdErrors(ef *errorsFixture) string {
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("class_name CourierErrorCode\n## 契约错误码(v1 冻结集);未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。\n\n")
	b.WriteString("## 域前缀注册表(新域先注册前缀再定义码)。\n")
	b.WriteString("const PREFIXES: PackedStringArray = [" + gdQuoteJoin(ef.Prefixes) + "]\n\n")
	b.WriteString("## 冻结映射:wire code → { http, retryable }。\n")
	b.WriteString("const SPECS: Dictionary = {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("\t\"%s\": {\"http\": %d, \"retryable\": %s},\n", c.Code, c.HTTP, lower(c.Retryable)))
	}
	b.WriteString("}\n\n")
	b.WriteString("const NAME_TO_WIRE: Dictionary = {\n")
	for _, c := range ef.Codes {
		b.WriteString(fmt.Sprintf("\t\"%s\": \"%s\",\n", camelName(c.Code), c.Code))
	}
	b.WriteString("}\n\n")
	b.WriteString("## wire code → 枚举名;未知返回 \"\"(调用方落兜底分支)。\n")
	b.WriteString("static func name_of(wire: String) -> String:\n\tfor name in NAME_TO_WIRE:\n\t\tif NAME_TO_WIRE[name] == wire:\n\t\t\treturn name\n\treturn \"\"\n\n")
	b.WriteString("static func spec_of(wire: String) -> Dictionary:\n\treturn SPECS.get(wire, {})\n")
	return b.String()
}

func genGdEnvelope(df *dtoFixture, sf *scopeFixture) string {
	k := df.Keys
	var b strings.Builder
	b.WriteString(genBanner)
	b.WriteString("class_name CourierEnvelope\n## 信封 wire key 常量与判定(primitives.md Frozen v1)。\n## GDScript 以 Dictionary 承载线格式,key 常量即 DTO 对齐锚点。\n\n")
	fmt.Fprintf(&b, `const KEY_DATA := "%s"      # 成功信封只有 data,不携带 traceId
const KEY_ERROR := "%s"     # 失败信封 error + traceId,与 data 互斥
const KEY_TRACE_ID := "%s"  # 只在失败响应 body
const KEY_CODE := "%s"
const KEY_MESSAGE := "%s"
const KEY_RETRYABLE := "%s"
const KEY_ITEMS := "%s"
const KEY_NEXT_CURSOR := "%s"  # 缺失/空 = 末页

# scope 头(game_id + env,scope.md Frozen v1):
const HEADER_GAME_ID := "%s"
const HEADER_ENV := "%s"
const ENVS: PackedStringArray = [%s]

static func is_failure(body: Dictionary) -> bool:
	return body.has(KEY_ERROR)

static func trace_id_of(body: Dictionary) -> String:
	return str(body.get(KEY_TRACE_ID, ""))
`, k["data"], k["error"], k["traceId"], k["code"], k["message"], k["retryable"],
		k["items"], k["nextCursor"],
		sf.Headers["gameId"], sf.Headers["env"], gdQuoteJoin(sf.Envs))
	return b.String()
}

// --- helpers ---

func lower(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func quoteJoin(ss []string) string {
	out := make([]string, 0, len(ss))
	for _, s := range ss {
		out = append(out, fmt.Sprintf("%q", s))
	}
	return strings.Join(out, ", ")
}

func tsQuoteJoin(ss []string) string  { return quoteJoin(ss) }
func cppQuoteJoin(ss []string) string { return quoteJoin(ss) }

func gdQuoteJoin(ss []string) string {
	out := make([]string, 0, len(ss))
	for _, s := range ss {
		out = append(out, fmt.Sprintf("\"%s\"", s))
	}
	return strings.Join(out, ", ")
}
