// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
#ifndef COURIER_CONTRACT_ENVELOPE_HPP
#define COURIER_CONTRACT_ENVELOPE_HPP

#include <string>
#include <vector>

namespace courier {

/// 失败响应 error 体(wire keys: code/message/retryable)。
struct ApiError {
    static constexpr const char* kKeyCode = "code";
    static constexpr const char* kKeyMessage = "message";
    static constexpr const char* kKeyRetryable = "retryable";
    std::string code;
    std::string message;
    bool retryable = false;
};

/// 失败信封:error + traceId,与 data 互斥;traceId 只在失败响应 body。
struct ErrorEnvelope {
    static constexpr const char* kKeyError = "error";
    static constexpr const char* kKeyTraceId = "traceId";
    ApiError error;
    std::string traceId;
};

/// 成功信封:只有 data,不携带 traceId。
template <typename T>
struct SuccessEnvelope {
    static constexpr const char* kKeyData = "data";
    T data;
};

/// 游标分页:items + nextCursor;缺失/空 = 末页。
template <typename T>
struct Page {
    static constexpr const char* kKeyItems = "items";
    static constexpr const char* kKeyNextCursor = "nextCursor";
    std::vector<T> items;
    std::string nextCursor;
};

}  // namespace courier

#endif  // COURIER_CONTRACT_ENVELOPE_HPP
