// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
#ifndef COURIER_CONTRACT_ERRORS_HPP
#define COURIER_CONTRACT_ERRORS_HPP

#include <cstddef>
#include <cstring>

namespace courier {

/// 契约错误码(v1 冻结集);未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。
enum class ErrorCode {
    CommonInternal = 0,
    CommonInvalidArgument = 1,
    CommonUnauthenticated = 2,
    CommonPermissionDenied = 3,
    CommonNotFound = 4,
    CommonCapabilityDisabled = 5,
    CommonUnavailable = 6,
    RateLimited = 7,
    ScopeMismatch = 8,
    AuthInvalidCredentials = 9,
    AuthTokenExpired = 10,
    AuthTokenRevoked = 11,
    AuthRefreshReused = 12,
    AuthAccountDisabled = 13,
    AuthDeviceLimit = 14,
    AuthEmailTaken = 15,
    SessionConflict = 16,
    AnnouncementNotFound = 17,
    SupportTicketNotFound = 18,
    SupportTicketClosed = 19,
    RealnameRequired = 20,
    RealnameRejected = 21,
    RealnamePendingReview = 22,
    RealnameCurfewBlocked = 23,
    RealnameChargeBlocked = 24,
    ConfigNotFound = 25,
    AppMaintenance = 26,
    AppVersionUnsupported = 27,
    kCount  // 哨兵,非契约码
};

struct ErrorSpec {
    const char* wire;
    int http;
    bool retryable;
};

/// 冻结映射:下标与 ErrorCode 枚举值对齐。
inline const ErrorSpec& error_spec(ErrorCode code) {
    static const ErrorSpec kSpecs[] = {
        {"COMMON_INTERNAL", 500, true},
        {"COMMON_INVALID_ARGUMENT", 400, false},
        {"COMMON_UNAUTHENTICATED", 401, false},
        {"COMMON_PERMISSION_DENIED", 403, false},
        {"COMMON_NOT_FOUND", 404, false},
        {"COMMON_CAPABILITY_DISABLED", 501, false},
        {"COMMON_UNAVAILABLE", 503, true},
        {"RATE_LIMITED", 429, true},
        {"SCOPE_MISMATCH", 400, false},
        {"AUTH_INVALID_CREDENTIALS", 401, false},
        {"AUTH_TOKEN_EXPIRED", 401, false},
        {"AUTH_TOKEN_REVOKED", 401, false},
        {"AUTH_REFRESH_REUSED", 401, false},
        {"AUTH_ACCOUNT_DISABLED", 403, false},
        {"AUTH_DEVICE_LIMIT", 403, false},
        {"AUTH_EMAIL_TAKEN", 409, false},
        {"SESSION_CONFLICT", 409, false},
        {"ANNOUNCEMENT_NOT_FOUND", 404, false},
        {"SUPPORT_TICKET_NOT_FOUND", 404, false},
        {"SUPPORT_TICKET_CLOSED", 409, false},
        {"REALNAME_REQUIRED", 403, false},
        {"REALNAME_REJECTED", 403, false},
        {"REALNAME_PENDING_REVIEW", 403, false},
        {"REALNAME_CURFEW_BLOCKED", 403, false},
        {"REALNAME_CHARGE_BLOCKED", 403, false},
        {"CONFIG_NOT_FOUND", 404, false},
        {"APP_MAINTENANCE", 503, false},
        {"APP_VERSION_UNSUPPORTED", 426, false},
    };
    return kSpecs[static_cast<std::size_t>(code)];
}

/// wire code → 枚举;未知返回 false(调用方落兜底分支)。
inline bool parse_error_code(const char* wire, ErrorCode& out) {
    for (int i = 0; i < static_cast<int>(ErrorCode::kCount); i++) {
        const ErrorSpec& s = error_spec(static_cast<ErrorCode>(i));
        if (std::strcmp(s.wire, wire) == 0) { out = static_cast<ErrorCode>(i); return true; }
    }
    return false;
}

/// 域前缀注册表(新域先注册前缀再定义码)。
inline const char* const* error_prefixes(std::size_t& count) {
    static const char* const kPrefixes[] = { "COMMON", "AUTH", "SESSION", "SCOPE", "RATE", "ANNOUNCEMENT", "SUPPORT", "ASSISTANT", "PAYMENT", "REALNAME", "CONFIG", "APP", "DIAG" };
    count = sizeof(kPrefixes) / sizeof(kPrefixes[0]);
    return kPrefixes;
}

}  // namespace courier

#endif  // COURIER_CONTRACT_ERRORS_HPP
