// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
/** 失败响应 error 体(wire keys: code/message/retryable)。 */
export interface ApiError {
  readonly code: string;
  readonly message: string;
  readonly retryable: boolean;
}

/** 失败信封:error + traceId,与 data 互斥;traceId 只在失败响应 body。 */
export interface ErrorEnvelope {
  readonly error: ApiError;
  readonly traceId: string;
}

/** 成功信封:只有 data,不携带 traceId。 */
export interface SuccessEnvelope<T> {
  readonly data: T;
}

/** 游标分页:items + nextCursor;缺失/空 = 末页。 */
export interface Page<T> {
  readonly items: readonly T[];
  readonly nextCursor?: string;
}
