// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
/** 契约错误码(wire 值);未知 code 必须容忍,落到兜底分支(契约 versioning.md)。 */
export const ErrorCode = {
  CommonInternal: "COMMON_INTERNAL",
  CommonInvalidArgument: "COMMON_INVALID_ARGUMENT",
  CommonUnauthenticated: "COMMON_UNAUTHENTICATED",
  CommonPermissionDenied: "COMMON_PERMISSION_DENIED",
  CommonNotFound: "COMMON_NOT_FOUND",
  CommonCapabilityDisabled: "COMMON_CAPABILITY_DISABLED",
  CommonUnavailable: "COMMON_UNAVAILABLE",
  RateLimited: "RATE_LIMITED",
  ScopeMismatch: "SCOPE_MISMATCH",
  AuthInvalidCredentials: "AUTH_INVALID_CREDENTIALS",
  AuthTokenExpired: "AUTH_TOKEN_EXPIRED",
  AuthTokenRevoked: "AUTH_TOKEN_REVOKED",
  AuthRefreshReused: "AUTH_REFRESH_REUSED",
  AuthAccountDisabled: "AUTH_ACCOUNT_DISABLED",
  AuthDeviceLimit: "AUTH_DEVICE_LIMIT",
  AuthEmailTaken: "AUTH_EMAIL_TAKEN",
  SessionConflict: "SESSION_CONFLICT",
  AnnouncementNotFound: "ANNOUNCEMENT_NOT_FOUND",
  SupportTicketNotFound: "SUPPORT_TICKET_NOT_FOUND",
  SupportTicketClosed: "SUPPORT_TICKET_CLOSED",
  RealnameRequired: "REALNAME_REQUIRED",
  RealnameRejected: "REALNAME_REJECTED",
  RealnamePendingReview: "REALNAME_PENDING_REVIEW",
  RealnameCurfewBlocked: "REALNAME_CURFEW_BLOCKED",
  RealnameChargeBlocked: "REALNAME_CHARGE_BLOCKED",
  ConfigNotFound: "CONFIG_NOT_FOUND",
  AppMaintenance: "APP_MAINTENANCE",
  AppVersionUnsupported: "APP_VERSION_UNSUPPORTED",
  PaymentSkuNotFound: "PAYMENT_SKU_NOT_FOUND",
  PaymentOrderNotFound: "PAYMENT_ORDER_NOT_FOUND",
  PaymentRiskRejected: "PAYMENT_RISK_REJECTED",
  PaymentInvalidSignature: "PAYMENT_INVALID_SIGNATURE",
  PaymentOrderState: "PAYMENT_ORDER_STATE",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorSpec {
  readonly wire: ErrorCode;
  readonly http: number;
  readonly retryable: boolean;
}

/** 冻结映射:错误码 → wire / HTTP / retryable。 */
export const ErrorSpecs: Readonly<Record<ErrorCode, ErrorSpec>> = {
  CommonInternal: { wire: "COMMON_INTERNAL", http: 500, retryable: true },
  CommonInvalidArgument: { wire: "COMMON_INVALID_ARGUMENT", http: 400, retryable: false },
  CommonUnauthenticated: { wire: "COMMON_UNAUTHENTICATED", http: 401, retryable: false },
  CommonPermissionDenied: { wire: "COMMON_PERMISSION_DENIED", http: 403, retryable: false },
  CommonNotFound: { wire: "COMMON_NOT_FOUND", http: 404, retryable: false },
  CommonCapabilityDisabled: { wire: "COMMON_CAPABILITY_DISABLED", http: 501, retryable: false },
  CommonUnavailable: { wire: "COMMON_UNAVAILABLE", http: 503, retryable: true },
  RateLimited: { wire: "RATE_LIMITED", http: 429, retryable: true },
  ScopeMismatch: { wire: "SCOPE_MISMATCH", http: 400, retryable: false },
  AuthInvalidCredentials: { wire: "AUTH_INVALID_CREDENTIALS", http: 401, retryable: false },
  AuthTokenExpired: { wire: "AUTH_TOKEN_EXPIRED", http: 401, retryable: false },
  AuthTokenRevoked: { wire: "AUTH_TOKEN_REVOKED", http: 401, retryable: false },
  AuthRefreshReused: { wire: "AUTH_REFRESH_REUSED", http: 401, retryable: false },
  AuthAccountDisabled: { wire: "AUTH_ACCOUNT_DISABLED", http: 403, retryable: false },
  AuthDeviceLimit: { wire: "AUTH_DEVICE_LIMIT", http: 403, retryable: false },
  AuthEmailTaken: { wire: "AUTH_EMAIL_TAKEN", http: 409, retryable: false },
  SessionConflict: { wire: "SESSION_CONFLICT", http: 409, retryable: false },
  AnnouncementNotFound: { wire: "ANNOUNCEMENT_NOT_FOUND", http: 404, retryable: false },
  SupportTicketNotFound: { wire: "SUPPORT_TICKET_NOT_FOUND", http: 404, retryable: false },
  SupportTicketClosed: { wire: "SUPPORT_TICKET_CLOSED", http: 409, retryable: false },
  RealnameRequired: { wire: "REALNAME_REQUIRED", http: 403, retryable: false },
  RealnameRejected: { wire: "REALNAME_REJECTED", http: 403, retryable: false },
  RealnamePendingReview: { wire: "REALNAME_PENDING_REVIEW", http: 403, retryable: false },
  RealnameCurfewBlocked: { wire: "REALNAME_CURFEW_BLOCKED", http: 403, retryable: false },
  RealnameChargeBlocked: { wire: "REALNAME_CHARGE_BLOCKED", http: 403, retryable: false },
  ConfigNotFound: { wire: "CONFIG_NOT_FOUND", http: 404, retryable: false },
  AppMaintenance: { wire: "APP_MAINTENANCE", http: 503, retryable: false },
  AppVersionUnsupported: { wire: "APP_VERSION_UNSUPPORTED", http: 426, retryable: false },
  PaymentSkuNotFound: { wire: "PAYMENT_SKU_NOT_FOUND", http: 404, retryable: false },
  PaymentOrderNotFound: { wire: "PAYMENT_ORDER_NOT_FOUND", http: 404, retryable: false },
  PaymentRiskRejected: { wire: "PAYMENT_RISK_REJECTED", http: 403, retryable: false },
  PaymentInvalidSignature: { wire: "PAYMENT_INVALID_SIGNATURE", http: 403, retryable: false },
  PaymentOrderState: { wire: "PAYMENT_ORDER_STATE", http: 409, retryable: false },
};

/** wire code → 枚举;未知返回 undefined(调用方落兜底分支)。 */
export function errorCodeOf(wire: string): ErrorCode | undefined {
  for (const key of Object.keys(ErrorSpecs) as ErrorCode[]) {
    if (ErrorSpecs[key].wire === wire) return key;
  }
  return undefined;
}

/** 域前缀注册表(新域先注册前缀再定义码)。 */
export const ERROR_PREFIXES = ["COMMON", "AUTH", "SESSION", "SCOPE", "RATE", "ANNOUNCEMENT", "SUPPORT", "ASSISTANT", "PAYMENT", "REALNAME", "CONFIG", "APP", "DIAG"] as const;
export type ErrorPrefix = (typeof ERROR_PREFIXES)[number];
