// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
//
namespace Courier.Contract
{
    /// <summary>失败响应 error 体(wire: code/message/retryable)。code 为 wire 字符串,未知码容忍。</summary>
    public sealed class ApiError
    {
        public const string KeyCode = "code";
        public const string KeyMessage = "message";
        public const string KeyRetryable = "retryable";
        public string Code { get; set; }
        public string Message { get; set; }
        public bool Retryable { get; set; }
    }

    /// <summary>失败信封(wire: error + traceId;与 data 互斥,traceId 只在失败响应 body)。</summary>
    public sealed class ErrorEnvelope
    {
        public const string KeyError = "error";
        public const string KeyTraceId = "traceId";
        public ApiError Error { get; set; }
        public string TraceId { get; set; }
    }

    /// <summary>成功信封(wire: 只有 data,不携带 traceId)。</summary>
    public sealed class SuccessEnvelope<T>
    {
        public const string KeyData = "data";
        public T Data { get; set; }
    }

    /// <summary>游标分页(items + nextCursor;缺失/空 = 末页)。</summary>
    public sealed class Page<T>
    {
        public const string KeyItems = "items";
        public const string KeyNextCursor = "nextCursor";
        public System.Collections.Generic.List<T> Items { get; set; }
        public string NextCursor { get; set; }
    }
}
