// Code generated by tools/contractgen from docs/contract/fixtures; DO NOT EDIT.
// 契约事实源:docs/contract/errors.md(Frozen v1)。重新生成:go run ./tools/contractgen -write
//
namespace Courier.Contract
{
    /// <summary>契约错误码(v1 冻结集)。未知 wire code 必须容忍,落到兜底分支(契约 versioning.md)。</summary>
    public enum ErrorCode
    {
        CommonInternal = 0,
        CommonInvalidArgument = 1,
        CommonUnauthenticated = 2,
        CommonPermissionDenied = 3,
        CommonNotFound = 4,
        CommonCapabilityDisabled = 5,
        CommonUnavailable = 6,
        RateLimited = 7,
        ScopeMismatch = 8,
        AuthInvalidCredentials = 9,
        AuthTokenExpired = 10,
        AuthTokenRevoked = 11,
        AuthRefreshReused = 12,
        AuthAccountDisabled = 13,
        AuthDeviceLimit = 14,
        AuthEmailTaken = 15,
        SessionConflict = 16,
        AnnouncementNotFound = 17,
        SupportTicketNotFound = 18,
        SupportTicketClosed = 19,
        RealnameRequired = 20,
        RealnameRejected = 21,
        RealnamePendingReview = 22,
        RealnameCurfewBlocked = 23,
        RealnameChargeBlocked = 24,
        ConfigNotFound = 25,
        AppMaintenance = 26,
        AppVersionUnsupported = 27,
    }

    /// <summary>错误码 → wire / HTTP / retryable 冻结映射(下标与枚举值对齐)。</summary>
    public static class ErrorSpecs
    {
        public sealed class Spec
        {
            public string Wire { get; }
            public int Http { get; }
            public bool Retryable { get; }
            internal Spec(string wire, int http, bool retryable) { Wire = wire; Http = http; Retryable = retryable; }
        }

        static readonly Spec[] Ordered =
        {
            new Spec("COMMON_INTERNAL", 500, true),
            new Spec("COMMON_INVALID_ARGUMENT", 400, false),
            new Spec("COMMON_UNAUTHENTICATED", 401, false),
            new Spec("COMMON_PERMISSION_DENIED", 403, false),
            new Spec("COMMON_NOT_FOUND", 404, false),
            new Spec("COMMON_CAPABILITY_DISABLED", 501, false),
            new Spec("COMMON_UNAVAILABLE", 503, true),
            new Spec("RATE_LIMITED", 429, true),
            new Spec("SCOPE_MISMATCH", 400, false),
            new Spec("AUTH_INVALID_CREDENTIALS", 401, false),
            new Spec("AUTH_TOKEN_EXPIRED", 401, false),
            new Spec("AUTH_TOKEN_REVOKED", 401, false),
            new Spec("AUTH_REFRESH_REUSED", 401, false),
            new Spec("AUTH_ACCOUNT_DISABLED", 403, false),
            new Spec("AUTH_DEVICE_LIMIT", 403, false),
            new Spec("AUTH_EMAIL_TAKEN", 409, false),
            new Spec("SESSION_CONFLICT", 409, false),
            new Spec("ANNOUNCEMENT_NOT_FOUND", 404, false),
            new Spec("SUPPORT_TICKET_NOT_FOUND", 404, false),
            new Spec("SUPPORT_TICKET_CLOSED", 409, false),
            new Spec("REALNAME_REQUIRED", 403, false),
            new Spec("REALNAME_REJECTED", 403, false),
            new Spec("REALNAME_PENDING_REVIEW", 403, false),
            new Spec("REALNAME_CURFEW_BLOCKED", 403, false),
            new Spec("REALNAME_CHARGE_BLOCKED", 403, false),
            new Spec("CONFIG_NOT_FOUND", 404, false),
            new Spec("APP_MAINTENANCE", 503, false),
            new Spec("APP_VERSION_UNSUPPORTED", 426, false),
        };

        /// <summary>域前缀注册表(新域先注册前缀再定义码)。</summary>
        public static readonly string[] Prefixes = { "COMMON", "AUTH", "SESSION", "SCOPE", "RATE", "ANNOUNCEMENT", "SUPPORT", "ASSISTANT", "PAYMENT", "REALNAME", "CONFIG", "APP", "DIAG" };

        /// <summary>全部冻结码(供契约测试对账)。</summary>
        public static System.Collections.Generic.IReadOnlyList<Spec> All
        {
            get { return Ordered; }
        }

        public static bool TryGet(ErrorCode code, out Spec spec)
        {
            int i = (int)code;
            if (i < 0 || i >= Ordered.Length) { spec = null; return false; }
            spec = Ordered[i]; return true;
        }

        /// <summary>wire code → 枚举;未知返回 false(调用方落兜底分支)。</summary>
        public static bool TryParse(string wire, out ErrorCode code)
        {
            for (int i = 0; i < Ordered.Length; i++)
            {
                if (Ordered[i].Wire == wire) { code = (ErrorCode)i; return true; }
            }
            code = default; return false;
        }
    }
}
